name: Tests
on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Run tests in all packages
        run: go test -v ./...
      - name: Build the binary
        run: go build .
      - name: Vet
        run: go vet ./...